### ISSUE TITLE
[TODO]: Add chronic conditions for the users

### ISSUE THREAD

**Issue by cbraidwood** [nutrition-monitoring-system/nhms#29]
Users need to be able to select symptoms and chronic conditions so they can get support and monitor progress.

**Comment by harrykeeran12** [comment]
Database:
- [x] The chronic conditions + symptoms have been added to the database.
- [x] Corresponding backend functions and tests have been added.

Frontend:
- [ ] A frontend for the symptoms page will be created. 
- [ ] A frontend to edit the chronic conditions of the user will be created.

**Comment by harrykeeran12** [comment]
This issue is redundant due to the removal of adding chronic conditions, the user is stuck with specific conditions.
