### ISSUE TITLE
[TODO]: Work on an implementation of the recipes that:

### ISSUE THREAD

**Issue by harrykeeran12** [nutrition-monitoring-system/nhms#48]
- [ ] Highlights Dr Gostic's recipes, in some way(pinning them to the top).
- [ ] Allows you to add a recipe to your collection, with a toast notification that you've added this item to a collection. 
- [ ] Properly takes data from the backend, for the recipes. 
- [ ] Allows you to filter each item, by the amount of time, or the colour(depending on your specific condition).
