### ISSUE TITLE
[TODO]: Add functionality to the admin dashboard. 

### ISSUE THREAD

**Issue by harrykeeran12** [nutrition-monitoring-system/nhms#53]
- [ ] The admin dashboard should have a list of all users, along with filtering capabilities by row. For this you could use this [table.](https://ui.shadcn.com/docs/components/data-table)
- [ ] The admin dashboard should have a list of all the symptoms, along with what articles are linked. 
- [ ] **Only people with admin access** should be able to access the dashboard.

**Comment by harrykeeran12** [comment]
@nann7 Would you be able to get this done? Basically you'd just need to add 2 buttons, which replace the content of the admin dashboard site with two tables, one with a list of all the symptoms, and the other with a list of all the users(you can use the table listed in the link above)

**Comment by nann7** [comment]
Ok, no problem!

**Comment by nann7** [comment]
Is it to create a new management page that only administrators can use? Or add it to our original application page.

**Comment by harrykeeran12** [comment]
> Is it to create a new management page that only administrators can use? Or add it to our original application page.

So this would be for the admin dashboard that we already have, which would have like a button which the admin could press, and then it shows a list of users, that the administrator could see and use. @nann7 If you have any questions please ask!

**Comment by harrykeeran12** [comment]
I've mocked up a basic design on Figma(don't worry about the sidenav bar I'll fix that in a bit), please make sure you're up to date with the main branch before you create a new branch @nann7

**Comment by nann7** [comment]
OK I see that. I would like to ask if the user list contains the user's name, account number and other information?

**Comment by harrykeeran12** [comment]
@nann7 It should contain everything that the selectAllUsers api returns(aka everything apart from the password), so if you use the *useSWR* hook, which returns the JSON output, you would get all the data. Currently the register function is not working though, so you might have to manually add data to your postgres database.

**Comment by harrykeeran12** [comment]
I've created the adminDashboard branch and added the table component. If you have any other questions please ask!

**Comment by nann7** [comment]
Ok, thank you!

**Comment by nann7** [comment]
<img width="780" alt="0232c2bf692b77108f5b8be93235f2b" src="https://github.com/nutrition-monitoring-system/nhms/assets/145394742/c8008a0b-7510-4cb6-bbfd-bf09b056e0cf">
<img width="780" alt="52e52fa666cfe82b65f701ac3e0d38a" src="https://github.com/nutrition-monitoring-system/nhms/assets/145394742/10102336-d05e-469a-b940-f5d02aa9cf2b">
<img width="780" alt="95d00f45bfc7e548721bab5c90d1390" src="https://github.com/nutrition-monitoring-system/nhms/assets/145394742/956c1cdc-699c-4b51-a359-b113ec4c44be">
Why is there this error saying that it does not match the TypeScript format?    
Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & RefAttributes<any>

**Comment by harrykeeran12** [comment]
You have to use the table like its a component import, and probably do it in the admin folder.
If you use components/ui/table in the import, the table is in there(provided you've done an npm ci recently and that your branch is up to date)

**Comment by harrykeeran12** [comment]
@nann7 could I ask you to also:

- [ ]  add the button to add and delete users? 
- [ ] add a button to promote a user to an admin? 

There are methods to add and delete a user, I'll make one to upgrade a user to be an admin.

- [ ] Also please use `tanstack-table` the version of react table you're using is old.

- [ ] The CSS should be designed by you using Tailwind *not Bootstrap* as it is a heavy library.

Ask if you have any questions.

**Comment by nann7** [comment]
Sorry, I would like to ask if it is possible to still use react table without tanstack-table. There is so much to change, and I make a lot of mistakes when I try it.

**Comment by harrykeeran12** [comment]
> Sorry, I would like to ask if it is possible to still use react table without tanstack-table. There is so much to change, and I make a lot of mistakes when I try it.

It would be better if we used the best version of the table. I'm sorry but we do still have time for you to attempt this. I would recommend watching videos.

**Comment by nann7** [comment]
I tried changing the code, but after finding errors, I tried to rewrite it. It is found that the useTable hook function of @tanstack/react-table cannot be used. I imported it correctly and reinstalled the dependencies. Don't know what's wrong.
<img width="737" alt="b6ccf595116b65bf42d96f051c42726" src="https://github.com/nutrition-monitoring-system/nhms/assets/145394742/af8cf433-7159-4786-9827-ef982d1441f7">

**Comment by harrykeeran12** [comment]
@nann7 
If you push it I can take a look at it?

**Comment by harrykeeran12** [comment]
> I tried changing the code, but after finding errors, I tried to rewrite it. It is found that the useTable hook function of @tanstack/react-table cannot be used. I imported it correctly and reinstalled the dependencies. Don't know what's wrong. <img alt="b6ccf595116b65bf42d96f051c42726" width="737" src="https://private-user-images.githubusercontent.com/145394742/313501964-af8cf433-7159-4786-9827-ef982d1441f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MTAwMjEsIm5iZiI6MTcxMDcwOTcyMSwicGF0aCI6Ii8xNDUzOTQ3NDIvMzEzNTAxOTY0LWFmOGNmNDMzLTcxNTktNDc4Ni05ODI3LWVmOTgyZDE0NDFmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QyMTA4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWMzNzkzMTljNGQ3MjRhMWFhNDQ1NThhMTk5MGRlYjI0N2VmN2MxNGJkYTg5OTBhZTQ2NTVhMzNiMmQ0ZmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yclEbbBE_wV14h8h7_OmmVQ81NdUynaQigBZOvKX7JI">

https://tanstack.com/table/latest/docs/framework/react/react-table

This link has your answer.

**Comment by nann7** [comment]
> > 我尝试更改代码，但在发现错误后，我尝试重写它。发现无法使用 @tanstack/react-table 的 useTable 钩子函数。我正确导入了它并重新安装了依赖项。不知道怎么了。<img alt="编号：b6ccf595116b65bf42d96f051c42726" width="737" src="https://private-user-images.githubusercontent.com/145394742/313501964-af8cf433-7159-4786-9827-ef982d1441f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MTAwMjEsIm5iZiI6MTcxMDcwOTcyMSwicGF0aCI6Ii8xNDUzOTQ3NDIvMzEzNTAxOTY0LWFmOGNmNDMzLTcxNTktNDc4Ni05ODI3LWVmOTgyZDE0NDFmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QyMTA4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWMzNzkzMTljNGQ3MjRhMWFhNDQ1NThhMTk5MGRlYjI0N2VmN2MxNGJkYTg5OTBhZTQ2NTVhMzNiMmQ0ZmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yclEbbBE_wV14h8h7_OmmVQ81NdUynaQigBZOvKX7JI">
> 
> https://tanstack.com/table/latest/docs/framework/react/react-table
> 
> 这个链接有你的答案。

I just watched this page and changed my code

**Comment by nann7** [comment]
I submitted it to github. I didn't change it based on my original one because I was worried that my changes would make a mess. So I created a new usertable1.jsx. The inside is newly modified by me. I'm very sorry, I tried all afternoon without success. Can you help take a look?
