### ISSUE TITLE
[TODO]: HCI aspects in the report.

### ISSUE THREAD

**Issue by harrykeeran12** [nutrition-monitoring-system/nhms#72]
- [ ] Do the user personas.
- [ ] Do the user stories.
- [ ] Explain the design process.
- [ ] Any other HCI related aspects(use Benyon book.)
